name: KramalCI

on:
  workflow_dispatch:

env:
  release: 0

jobs:
  build:
    runs-on: ubuntu-latest
    container: nexgang/ubuntu:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Kernel
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "$release" -eq 1 ]; then
            echo "🚀 Release build selected!"
            cd && git clone --depth=1 https://${GH_TOKEN}@github.com/reaPeR1010/kernel_4.14 -b nonksu y
            cd y
            curl -Ls https://gist.githubusercontent.com/reaPeR1010/4b5e27fbcb2d25eebe08e7a5e0d4038a/raw/xxx.sh | bash -s nonksu
            cd && git clone --depth=1 https://${GH_TOKEN}@github.com/reaPeR1010/kernel_4.14 -b susfs z
            cd z
            curl -Ls https://gist.githubusercontent.com/reaPeR1010/4b5e27fbcb2d25eebe08e7a5e0d4038a/raw/xxx.sh | bash -s susfs
            cd && git clone --depth=1 https://${GH_TOKEN}@github.com/reaPeR1010/kernel_4.14 -b miui r
            cd r
            curl -Ls https://gist.githubusercontent.com/reaPeR1010/4b5e27fbcb2d25eebe08e7a5e0d4038a/raw/xxx.sh | bash -s miui-ksu
          else
            echo "⚙️ Normal build selected."
            git clone --depth=1 https://${GH_TOKEN}@github.com/reaPeR1010/kernel_4.14 -b main x
            cd x
            curl -Ls https://gist.githubusercontent.com/reaPeR1010/4b5e27fbcb2d25eebe08e7a5e0d4038a/raw/xxx.sh | bash -s ksu
          fi
